openapi: 3.0.1
info:
  title: GFT Test API
  version: 1.0.0
paths:
  /prices:
    get:
      summary: REST endpoint for querying
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
