spring:
  application:
    name: gft

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /
    urls:
      - url: /api/prices.yml
        name: Prices API

