spring:
  application:
    name: gft
  datasource:
    url: jdbc:postgresql://localhost:5432/prices_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml

logging:
  file:
    name: target/logs/gft.log

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /
    urls:
      - url: /api/prices.yml
        name: Prices API
